name: sdt-conda-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gdal>=3.8.5,<3.9.0
  - rasterio>=1.3.9,<1.4.0
  - shapely>=2.0.3,<2.1.0
  - jsonschema>=4.21.0,<4.22.0
  - pystac>=1.9.0,<1.10.0
  - pydantic-settings>=2.2.1,<2.3.0
  - azure-storage-blob>=12.19.1,<12.20.0
  - mkdocs>=1.6.1,<1.7.0
  - mkdocs-material>=9.6.20,<9.7.0
  - mkdocstrings>=0.30.0,<0.31.0
  - pyyaml>=6.0.2,<7.0
  - python-dotenv>=1.1.1,<2.0.0
  - pymdown-extensions>=10.16.1,<11.0.0
  - pip
  - pip:
      - flake8==7.1.1
      - pycodestyle==2.12.1
      - pyflakes==3.2.0
      - mccabe==0.7.0
      - black==24.3.0
      - isort==5.13.2
      - autoflake==2.3.1
      - autopep8==2.3.1





