site_name: stac-data-tools

theme:
  name: material
  features:
    - content.code.copy   # botón copiar

plugins:
  - search
  - markdown-exec

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - tables

nav:
  - Inicio: index.md
  - Guía principal: main.md
  - Referencia CLI:
      - Comandos: cli.md

