name: Check code format

on:
  pull_request:
    branches:
      - main

jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Black format check
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./main.py"
