name: Flake8 Lint

on:
  pull_request:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "src"
